### ISSUE TITLE
Consider grouping entities into a device for HA MQTT autodiscovery

### ISSUE THREAD

**Issue by djwillis** [Achronite/mqtt-energenie-ener314rt#15]
Hi,

Thanks so much for this, it is working so well and is such a nice way to clean up and simplify the ener314rt intergration.

The recent addition off the HA autodiscovery for FSK devices is so nice and this is not really an issue, more a feature request.

Is it possible to expand the Home Assistant MQTT discovery code to group the related entities into a logical device?

Something like the following added/duplicated in the vairous payloads for the individual entities seems to be enough to let HA create all the logical aggrigation so you end up with a single device with all the entites grouped underneath.

  "device": {
    "identifiers": [
      "ener314rt-xxxx"
    ],
    "name": "ener314rt-xxxx",
    "model": "Smart Plug+",
    "manufacturer": "mqtt-energenie-ener314rt",
    "sw_version": "0.0.1"
  },
  
Not had a chance to tweak the code to test this for mqtt-energenie-ener314rt and it will be a few nights before I have time, so I thought I would ask here in case there is a very solid reason not to do it or ir was something already on your radar.

In a similar vien, if the TRV sensors got grouped up per device then would it make sense to use a climate sensor type for the TRV target temp so they can be used as direct climate devices. Actually, I suspect that may be a pain but i'll leave the idea lingering.

Thanks again,

John

**Comment by Achronite** [comment]
> Is it possible to expand the Home Assistant MQTT discovery code to group the related entities into a logical device?

Sounds like a good idea - I'm new to Home Assistant and I was wondering how do that kind of grouping!

>In a similar vain, if the TRV sensors got grouped up per device then would it make sense to use a climate sensor type for the TRV target temp

How do you do this? Can you show an example?

**Comment by Achronite** [comment]
Is this what you mean for standard grouping? (WIP)

![image](https://user-images.githubusercontent.com/10363609/214665405-41baf62f-744d-4ff4-9454-c647468b4563.png)

Interestingly it drops the device name from the params, here is the real power config entry...
```
{
    "device": {
        "name": "Smart Plug+ 8294",
        "ids": [
            "ener314rt-8294"
        ],
        "mdl": "Smart Plug+",
        "mf": "energenie",
        "sw": "mqtt-ener314rt"
    },
    "uniq_id": "ener314rt-8294-REAL_POWER",
    "~": "energenie/",
    "name": "Smart Plug+ 8294 real_power",
    "dev_cla": "power",
    "unit_of_meas": "W",
    "stat_t": "~2/8294/REAL_POWER/state"
}
```

**Comment by djwillis** [comment]
Fairly sure the change came in to HA a while back, yep, it removes the main device name string if you have other text in the entities names and view the entities in some of the UI (not all of them I seem to recall). Plenty of scope to get obsessive with nameing I guess.

That is just what I was thinking about with the device grouping.  Looks spot on 👍

**Comment by Achronite** [comment]
Basic grouping has released to [develop](https://github.com/Achronite/mqtt-energenie-ener314rt/tree/develop) branch.  A new issue has been created for eTRV climate.

Will close on release to production
