### ISSUE TITLE
Add support for Thermostatic Radiator Valves

### ISSUE THREAD

**Issue by Achronite** [Achronite/mqtt-energenie-ener314rt#2]
Allow commands to be passed to eTRV, utilising the command caching as applicable.

**Comment by Achronite** [comment]
Now added to code, also includes MQTT discovery.

README still requires updating.

@dansgalaxy, @genestealer

**Comment by genestealer** [comment]
Have you looked into setting up a regular repeating query to ask the eTRV's for their battery voltage (once a day) and to excises their valves (weekly)?

I think I may implement it via a automation from home assistant, but........... There is a chance the two commands may overwrite another "more important" command, such as Set_Temp,.

Perhaps we need a way to queue commands for a eTRV and only certain commands (set temp, set valve state, etc) can overwrite each other.

**Comment by genestealer** [comment]
_* certain commands (set temp, set valve state, etc) can overwrite each other._
What I mean is, two set_temp's will overwrite each over, but a a set_valve's command will not overwrite the set_temp, rather, it will be queued.

**Comment by Achronite** [comment]
Updated the README - but basically only 1 COMMAND can be cached/queued for each TRV, including a Temperature change.

**Comment by Achronite** [comment]
> Have you looked into setting up a regular repeating query to ask the eTRV's for their battery voltage (once a day) and to excises their valves (weekly)?
Could do... DIAGNOSTICS would be a good one to call periodically;  I could probably work out when to do this when other commands are done to avoid overwriting the users commands (say when retries reaches 0).

I can't remember if VOLTAGE gets auto reported anyway...

**Comment by Achronite** [comment]
Created an issue to investigate periodic reporting #10
