### ISSUE TITLE
MIHO004 /VOLTAGE/state and /REAL_POWER/state?

### ISSUE THREAD

**Issue by genestealer** [Achronite/mqtt-energenie-ener314rt#32]
I notice on the MQTT Topics table for the MIHO004, the /VOLTAGE/state and /REAL_POWER/state are crossed out?
Why is this, as I can pull this info using your Node-Red code, in my implementation https://github.com/genestealer/node-red-energenie-ener314rt-home-assistant-mqtt

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/cbe74833-1eeb-46ad-b2a1-2cabd86d31fe)

**Comment by Achronite** [comment]
I left out the voltage because it is the mains voltage (as opposed to battery voltage) and never changes.

For REAL_POWER I guess i just missed it :) - I'll add it.

**Comment by Achronite** [comment]
Strike that - REAL_POWER is already shown as 'Power', as it has a device_class of 'power' assigned to it (there isn't a separate device_class for 'real power'). https://www.home-assistant.io/integrations/sensor/
