### ISSUE TITLE
motion sensor not sending home assistant discovery packets

### ISSUE THREAD

**Issue by webash** [Achronite/mqtt-energenie-ener314rt#36]
Hey there - thanks a billion for this work. Allows me to stop using my janky python library I wrote years ago on top of @whaleygeek's library.

Just set this up, and I've got it working nicely, and I can see everything I'd expect in the raw `energenie` topic; but for some reason there doesn't seem to be any discovery info sent to the `homeassistant` topic for the Energenie motion sensor I have. Its in the raw topic, but not discovery. 

Anything I should be looking out for?

**Comment by webash** [comment]
Nevermind, seems I was just too impatient and hadn't triggered the sensor enough for it to have a discovery packet sent yet. Has come up now after about 30 min of it running.

**Comment by Achronite** [comment]
Discovery messages are sent every 10 minutes during normal running. The motion sensor only sends out a packet if it detects/clears motion, so 20 mins is usually long enough to wait for it to appear.  Glad you got it sorted. :)

**Comment by webash** [comment]
Thanks again :)
