### ISSUE TITLE
Unsupported engine in NPM install?

### ISSUE THREAD

**Issue by genestealer** [Achronite/mqtt-energenie-ener314rt#44]
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/8adea6c0-7d3c-4dc9-96bf-14f8bede96b5)

Could you offer any tips?

Am I downloading an old version?
"wget https://github.com/Achronite/mqtt-energenie-ener314rt/archive/refs/heads/master.zip"

When trying to run anyway I get
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/c8f7193b-d26a-478e-b6cc-c4d8b82b1abd)

**Comment by genestealer** [comment]
Just a note, I had to uninstall nodejs in order to install npm. This pi previously was running my node red installation. Is the best cause of action to do a clean install?

**Comment by Achronite** [comment]
You now need nodejs v15+ to run and install mqtt-energenenie-ener314rt.  I had to bump the overall nodejs version when the MQTT module library (which I use) needed it.  I would just install the latest nodejs version and retry.

**Comment by genestealer** [comment]
Ok thanks,
I will follow https://github.com/nodesource/distributions#debian-versions to install nodejs:

### Installation Instructions

#### **Node.js**

1. Download and import the Nodesource GPG key

```sh
sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
```

2. Create deb repository

```sh
NODE_MAJOR=20
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
```

3. Run Update and Install

```sh
sudo apt-get update
sudo apt-get install nodejs -y
```

**Comment by genestealer** [comment]
Note, I had to remove the `mqtt-energenie-ener314rt` folder then run `npm install` again. As just re-running `npm install` did not update the MQTT version, even after upgrading to nodejs v15+.

Yay!! Seems to be working! :)

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/372a9584-9786-4a9a-bbfa-e7462a444342)

**Comment by genestealer** [comment]
PR raised on documentation to hopefully avoid simulare future issues.
https://github.com/Achronite/mqtt-energenie-ener314rt/pull/45
