### ISSUE TITLE
Merge/contribute project efforts 

### ISSUE THREAD

**Issue by genestealer** [Achronite/mqtt-energenie-ener314rt#46]
Hi, firstly this is fantastic work and thank you for making this. :)

I would migrate over from my node-red instance (using node-red-contrib-energenie-ener314rt) to mqtt-energenie-ener314rt but I notice I added some extra functionality into my MQTT discovery on node-red, which I would like to suggest we add into this.

My repo: https://github.com/genestealer/node-red-energenie-ener314rt-home-assistant-mqtt

Happy to make all the changes and then submit a pull request.

3. Smart Plug Plus (MIHO005) and Smart Monitor Plug (MIHO004) don't seem to be reporting all their data on your code:
Mine:
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/7b2623d9-4cae-4e6d-aad4-6a40ed05ad36)
Yours:
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/b8446f45-bd58-40de-ae99-f8bb8c17d7fc)

**Comment by genestealer** [comment]
Removed 1 and 2 and I see this was already completed, my mistake :(

**Comment by genestealer** [comment]
Work complete. PR raised. Please let me know if your unhappy with anything :)

https://github.com/Achronite/mqtt-energenie-ener314rt/pull/48

**Comment by genestealer** [comment]
New PR raised: https://github.com/Achronite/mqtt-energenie-ener314rt/pull/51

**Comment by Achronite** [comment]
Reopened as will be closed when released to master

**Comment by Achronite** [comment]
@genestealer Please take a look at develop, I think I've finished my updates.

NOTE: You didn't fix the VALVE_STATE number, you had HA heat = eTRV open (0) instead of HA heat = eTRV auto (2)

**Comment by genestealer** [comment]
> @genestealer Please take a look at develop, I think I've finished my updates.
> 
> NOTE: You didn't fix the VALVE_STATE number, you had HA heat = eTRV open (0) instead of HA heat = eTRV auto (2)

Thank you, will look now.
