### ISSUE TITLE
Devices stop receiving commands

### ISSUE THREAD

**Issue by Achronite** [Achronite/mqtt-energenie-ener314rt#5]
I've experienced a bug a couple of times whilst running the MQTT app for a while with monitoring enabled.  It seems that devices can stop receiving commands correctly, yet the transmit light is still illuminating, and it is still receiving monitor messages from the devices.

I've not experienced this issue before with the node-red implementation.

**Comment by Achronite** [comment]
Could be linked to https://github.com/Achronite/energenie-ener314rt/issues/23 ?

**Comment by Achronite** [comment]
Hoping the driver rewrite has fixed this, closing for now.  See related issue above for updates.

**Comment by dansgalaxy** [comment]
I seem to be having this issue currently despite the changes mentioned. It seems after less than 1 day running it stops working, as noted can see commands in the log, the light flashes on the ener314rt... but nothing happens with the switches. 

Current workaround seems to be just to restart the service which seems to get it all working again.

**Comment by Achronite** [comment]
@dansgalaxy Have you tried with the new release I made yesterday of [energenie-ener314rt](https://github.com/Achronite/energenie-ener314rt)?

Do you know if you are using software or hardware driver mode (it should be shown early in logs)?

**Comment by dansgalaxy** [comment]
@Achronite Pulled in latest changes and enabled hardware driver now.

Will update if any further issues, thanks!
