### ISSUE TITLE
Add option to config to enable or disable voltage and frequency reporting

### ISSUE THREAD

**Issue by genestealer** [Achronite/mqtt-energenie-ener314rt#54]
Add option to the config file, to change the default enabled or disabled behaviour for reporting frequency and voltage on monitor and control plugs.

I could think of a few ways to implement this: just having two json files for the plugs, or manipulating the data based upon the setting in the config file. 
Which do you think is the easiest approach?

**Comment by Achronite** [comment]
It seems a little redundant to me. If the user wants to enable them they only have to go into the HA config for the device and enable them.
