### ISSUE TITLE
MQTT Discovery messages are not sent out on a regular basis

### ISSUE THREAD

**Issue by genestealer** [Achronite/mqtt-energenie-ener314rt#60]
As the MQTT discovery messages do not appear to be sent out on a regular basis, details are lost until the service is manually rebooted or the Pi is restarted.

Is this just my experience or is this the behaviour that you also see?

**Comment by Achronite** [comment]
As it says in the README the discovery messages are sent every 30 mins after the initial ones. I did this deliberately for performance reasons.
