### ISSUE TITLE
Note: node version 18.2.0 now needed

### ISSUE THREAD

**Issue by genestealer** [Achronite/mqtt-energenie-ener314rt#77]
Please note, installing the 'develop' branch of mqtt-energenie-ener314rt I saw the warning regarding the insatlled node version. 

Current readme asks for "node.js v15+" however npn install asks for `required: { node: '>=18.2.0' `

```command
pi@raspberrypi:~/mqtt-energenie-ener314rt-develop $ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fast-unique-numbers@9.0.0',
npm WARN EBADENGINE   required: { node: '>=18.2.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/11a9c1d0-c3ed-4174-9161-04f90a7c0b14)

**Comment by genestealer** [comment]
@Achronite All tested and works great without needing to delete `package-lock.json`

**Comment by Achronite** [comment]
Code fully released now. Thanks for the help @genestealer! 😊
