### ISSUE TITLE
Add support for MiHome Click

### ISSUE THREAD

**Issue by Achronite** [Achronite/mqtt-energenie-ener314rt#79]
Does anyone out there own a MiHome Click that you could send me the message details on so I can add support for it?

@dansgalaxy , @genestealer , @webash , @mprocte1

**Comment by genestealer** [comment]
Sorry no I don't :(

**Comment by webash** [comment]
Me neither, sorry. Does anyone know where you can even buy this stuff these days?

**Comment by genestealer** [comment]
Screwfix sell the click, seems rather overpriced. But, they do offer 30 day
returns so someone could buy it and then return it as long as it still in
an unused condition.
