### ISSUE TITLE
Add "New Version" update information / Integrate MQTT Update

### ISSUE THREAD

**Issue by genestealer** [Achronite/mqtt-energenie-ener314rt#80]
I'm using [Raspberry Pi MQTT Monitor](https://github.com/hjelev/rpi-mqtt-monitor) and noticed they have very cleverly implemented [MQTT Update](https://www.home-assistant.io/integrations/update.mqtt/) which shows the user a notice in Home Assistant when a new github version is released. 
I thought it would be great to add this feature too.

> The mqtt Update platform allows you to integrate devices that might expose firmware/software installed and the latest versions through MQTT into Home Assistant as an Update entity. Every time a message under the topic in the configuration is received, the entity will be updated in Home Assistant.

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/3613f970-ae02-48fe-b79a-7fd18f949877)
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/46ef2b05-7c84-47b8-8cbd-dd2bee24d4ff)
https://github.com/hjelev/rpi-mqtt-monitor/releases/tag/0.8.3

**Comment by genestealer** [comment]
I see they have implemented an MQTT command to auto-update the scripts running on Pi, which may be a step too far, an update warning/notice would be nice though. 

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/5207490/929cbd69-d5ac-4124-95a3-780f3e7d004e)

**Comment by Achronite** [comment]
Almost there....
![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/10363609/1e3b9b5c-b64b-4ccf-8004-b645ea3d70ad)

**Comment by Achronite** [comment]
@genestealer Can you give the `develop` branch a test please to see if it meets your suggestion (bar the 'install' button, obviously).
